# Generated by Django 5.1.7 on 2025-12-17 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleProfileConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False, help_text='Does this role require a profile?')),
                ('model_path', models.CharField(blank=True, help_text="e.g., 'studentsdb.Student'. Leave empty for Generic Profile.", max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_config', to='rbac.role')),
            ],
        ),
        migrations.CreateModel(
            name='GenericProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generic_profile', to=settings.AUTH_USER_MODEL)),
                ('role_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.roleprofileconfig')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal field name (key)', max_length=100)),
                ('label', models.CharField(help_text='Display label', max_length=255)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('BOOLEAN', 'Boolean'), ('CHOICE', 'Choice (Dropdown)')], default='TEXT', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list, help_text='List of options for CHOICE type')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_fields', to='profiles.roleprofileconfig')),
            ],
            options={
                'unique_together': {('config', 'name')},
            },
        ),
    ]
