# Generated by Django 6.0 on 2026-01-07 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_must_change_password'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseUser',
            fields=[
            ],
            options={
                'verbose_name': 'Enterprise User (Onboarding)',
                'verbose_name_plural': 'Enterprise Users (Onboarding)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
        ),
    ]
