# Generated by Django 6.0 on 2026-01-27 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0006_alter_onboardrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UIModule',
            fields=[
                ('slug', models.SlugField(help_text="Unique identifier for the module (e.g., 'dashboard')", primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Human readable name', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('schema_def', models.JSONField(blank=True, default=dict, help_text='JSON Schema to validate configs against')),
            ],
        ),
        migrations.CreateModel(
            name='RoleUIDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(help_text='JSON configuration for the UI')),
                ('version', models.IntegerField(default=1, help_text='Config version for migration/cache busting')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ui_defaults', to='rbac.role')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_defaults', to='ui_engine.uimodule')),
            ],
            options={
                'verbose_name': 'Role UI Default',
                'verbose_name_plural': 'Role UI Defaults',
                'unique_together': {('role', 'module')},
            },
        ),
    ]
