# Generated by Django 6.0 on 2026-01-27 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_alter_onboardrequest_status'),
        ('ui_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUIPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(help_text='User personalized JSON configuration')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='ui_engine.uimodule')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='rbac.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ui_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User UI Preference',
                'verbose_name_plural': 'User UI Preferences',
                'unique_together': {('user', 'role', 'module')},
            },
        ),
    ]
