# Generated by Django 6.0 on 2026-02-06 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdb', '0003_alter_student_pgpassout_alter_student_ugpassout'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_currently_employed', models.BooleanField(default=False)),
                ('has_prior_work_experience', models.BooleanField(default=False)),
                ('current_employment_details', models.JSONField(blank=True, default=dict, help_text='Company, Role, CTC, Notice Period, etc.')),
                ('prior_experience_details', models.JSONField(blank=True, default=dict, help_text='Previous Companies, Tenure, Gaps')),
                ('technical_experience_profile', models.JSONField(blank=True, default=dict, help_text='Skills, Projects, Complexity')),
                ('fresher_readiness_profile', models.JSONField(blank=True, default=dict, help_text='Internships, Certifications, Academic Projects')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to='studentsdb.student')),
            ],
        ),
    ]
