# Generated by Django 6.0 on 2026-01-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_active_role',
            field=models.CharField(blank=True, help_text='Code of the last role the user accessed', max_length=50, null=True),
        ),
    ]
