# Generated by Django 6.0 on 2026-01-03 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='updated_by',
            field=models.ForeignKey(help_text='User who last updated this role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(help_text='Short role code (e.g., AD, TR). Immutable.', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='RoleSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_sequence', models.PositiveIntegerField(default=0, help_text='The last used number')),
                ('prefix_override', models.CharField(blank=True, help_text='Optional override for the default role code prefix', max_length=10, null=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(help_text='User who triggered the last ID generation', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sequence', to='rbac.role')),
            ],
        ),
    ]
