# Generated by Django 6.0 on 2026-01-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_onboardrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardrequest',
            name='status',
            field=models.CharField(choices=[('INVITED', 'Invited'), ('PENDING_APPROVAL', 'Pending Approval'), ('ONBOARDED', 'Onboarded'), ('DROPPED', 'Dropped')], default='INVITED', max_length=30),
        ),
    ]
