# Generated by Django 5.2.4 on 2026-02-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0007_add_permission_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description for tooltips.', null=True),
        ),
    ]
