# Generated by Django 6.0 on 2026-02-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_city_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='emoji',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso_code_2',
            field=models.CharField(db_index=True, max_length=2, unique=True),
        ),
    ]
